services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern
    depends_on:
      - mongodb

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - mern
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
networks:
  mern:
    driver: bridge
   

volumes:
  mongo-data:
    driver: local